In [29]:
import numpy as np

In [30]:
#Создайте двумерный массив 10x3, заполненный случайными значениями. В каждой строке выберите значение, наиболее близкое к 0.5.
a = np.random.random (30).reshape (10, 3)
#print(a)
print (np.take_along_axis (a, np.argmin (abs(a-0.5), axis=1).reshape(10, 1), axis=1))

[[0.73018687]
 [0.86595705]
 [0.35987071]
 [0.47501665]
 [0.34905241]
 [0.55388253]
 [0.45971297]
 [0.24271924]
 [0.64483941]
 [0.33826077]]


In [31]:
#Создайте двумерный массив 6x6, заполненный случайными значениями. Затем сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом.
a = np.random.random (36).reshape (6, 6)
#print(a, '\n\n')
print (np.sum (a, axis=1)/np.min (a, axis=0), '\n\n')            # если хотим сумму в i-ой строчке делить на минимум в i-ом столбце
#print (np.sum (a, axis=1).reshape(6,1)/np.min (a, axis=0))      # если хотим сумму в каждой строчке делить на минимум в каждом из столбцов

[21.88009112 19.03396917 34.62460524 22.33429416  9.92247219 11.86658617] 




In [32]:
#На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print (np.max (np.lib.stride_tricks.as_strided(x, shape=(np.size(x)-1, 2), strides=(4, 4)) [np.lib.stride_tricks.as_strided(x, shape=(np.size(x)-1, 2), strides=(4, 4))[:, 0] == 0] [:, 1]))

5


In [33]:
#Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.
x = np.ones(10) 
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x[np.unique (i, return_counts = True)[0]] += np.unique (i, return_counts = True)[1] # предполагаем корректные входные данные
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [34]:
# Написать функцию, реализующую алгоритм k-means. Входные и выходные значения функции должны быть аналогичны https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.cluster.vq.kmeans.html. Функция должна содержать не более двух циклов while (for).
def kmeans(points, k_or_guess, iter=20, thresh=1e-5, dist = -1):
    count_points = np.shape(points)[0]
    if (iter <= 0 or thresh < 0):
        raise
        
    if type (k_or_guess) == type (np.array ([])):
        centers = k_or_guess
        count_centers = np.shape (k_or_guess)[0]
    elif type (k_or_guess) == int:
        count_centers = k_or_guess
        centers = points[np.random.choice (count_points, count_centers, replace = False)]
    else:
        raise
    
    if (np.shape(centers)[1] != np.shape(points)[1]):
        raise
        
    x = centers[[np.argmin( np.sum((centers-i)**2, axis = 1)) for i in points]]
    centers, y = np.unique(x, axis=0, return_inverse=True)
    
    new_dist = 0
    new_centers = np.zeros (np.shape(centers))
    points_sq = 0
    points_sum = 0
    for i in range (count_points):
        new_dist += np.sum ((points[i] - centers[y[i]])**2)
        new_centers[y[i]] += points[i]/np.count_nonzero (y==y[i])
    new_dist = np.sum((points - new_centers[y])**2)

    if ( (dist >= 0 and dist-new_dist<thresh) or iter == 1):
        return new_centers, new_dist
    return kmeans (points, new_centers, iter-1, thresh, new_dist)